export const dummyCategories = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    icon: '📱',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400',
    description: 'Mobile phones, laptops, gadgets and more',
    isActive: true,
    order: 1,
    subcategories: [
      { id: '1-1', name: 'Mobile Phones', slug: 'mobile-phones' },
      { id: '1-2', name: 'Laptops', slug: 'laptops' },
      { id: '1-3', name: 'Tablets', slug: 'tablets' },
      { id: '1-4', name: 'Accessories', slug: 'accessories' },
    ],
    _count: { ads: 245 }
  },
  {
    id: '2',
    name: 'Vehicles',
    slug: 'vehicles',
    icon: '🚗',
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400',
    description: 'Cars, bikes, scooters and more',
    isActive: true,
    order: 2,
    subcategories: [
      { id: '2-1', name: 'Cars', slug: 'cars' },
      { id: '2-2', name: 'Bikes', slug: 'bikes' },
      { id: '2-3', name: 'Scooters', slug: 'scooters' },
    ],
    _count: { ads: 189 }
  },
  {
    id: '3',
    name: 'Furniture',
    slug: 'furniture',
    icon: '🪑',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
    description: 'Home furniture and decor',
    isActive: true,
    order: 3,
    subcategories: [
      { id: '3-1', name: 'Sofas', slug: 'sofas' },
      { id: '3-2', name: 'Tables', slug: 'tables' },
      { id: '3-3', name: 'Beds', slug: 'beds' },
    ],
    _count: { ads: 156 }
  },
  {
    id: '4',
    name: 'Fashion',
    slug: 'fashion',
    icon: '👕',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400',
    description: 'Clothing, shoes, accessories',
    isActive: true,
    order: 4,
    subcategories: [
      { id: '4-1', name: 'Men\'s Wear', slug: 'mens-wear' },
      { id: '4-2', name: 'Women\'s Wear', slug: 'womens-wear' },
      { id: '4-3', name: 'Shoes', slug: 'shoes' },
    ],
    _count: { ads: 312 }
  },
  {
    id: '5',
    name: 'Books',
    slug: 'books',
    icon: '📚',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    description: 'Books, magazines, comics',
    isActive: true,
    order: 5,
    subcategories: [
      { id: '5-1', name: 'Fiction', slug: 'fiction' },
      { id: '5-2', name: 'Non-Fiction', slug: 'non-fiction' },
      { id: '5-3', name: 'Academic', slug: 'academic' },
    ],
    _count: { ads: 98 }
  },
  {
    id: '6',
    name: 'Sports',
    slug: 'sports',
    icon: '⚽',
    image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400',
    description: 'Sports equipment and gear',
    isActive: true,
    order: 6,
    subcategories: [
      { id: '6-1', name: 'Fitness', slug: 'fitness' },
      { id: '6-2', name: 'Outdoor', slug: 'outdoor' },
      { id: '6-3', name: 'Water Sports', slug: 'water-sports' },
    ],
    _count: { ads: 134 }
  },
  {
    id: '7',
    name: 'Appliances',
    slug: 'appliances',
    icon: '🔌',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    description: 'Home appliances and electronics',
    isActive: true,
    order: 7,
    subcategories: [
      { id: '7-1', name: 'Kitchen', slug: 'kitchen' },
      { id: '7-2', name: 'Washing', slug: 'washing' },
      { id: '7-3', name: 'Cooling', slug: 'cooling' },
    ],
    _count: { ads: 201 }
  },
  {
    id: '8',
    name: 'Real Estate',
    slug: 'real-estate',
    icon: '🏠',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400',
    description: 'Properties for rent and sale',
    isActive: true,
    order: 8,
    subcategories: [
      { id: '8-1', name: 'For Sale', slug: 'for-sale' },
      { id: '8-2', name: 'For Rent', slug: 'for-rent' },
      { id: '8-3', name: 'Commercial', slug: 'commercial' },
    ],
    _count: { ads: 167 }
  },
];

export const dummyLocations = [
  { id: '1', name: 'Mumbai', slug: 'mumbai', state: 'Maharashtra', city: 'Mumbai', _count: { ads: 1234 } },
  { id: '2', name: 'Delhi', slug: 'delhi', state: 'Delhi', city: 'Delhi', _count: { ads: 987 } },
  { id: '3', name: 'Bangalore', slug: 'bangalore', state: 'Karnataka', city: 'Bangalore', _count: { ads: 856 } },
  { id: '4', name: 'Hyderabad', slug: 'hyderabad', state: 'Telangana', city: 'Hyderabad', _count: { ads: 743 } },
  { id: '5', name: 'Chennai', slug: 'chennai', state: 'Tamil Nadu', city: 'Chennai', _count: { ads: 654 } },
  { id: '6', name: 'Pune', slug: 'pune', state: 'Maharashtra', city: 'Pune', _count: { ads: 542 } },
  { id: '7', name: 'Kolkata', slug: 'kolkata', state: 'West Bengal', city: 'Kolkata', _count: { ads: 489 } },
  { id: '8', name: 'Ahmedabad', slug: 'ahmedabad', state: 'Gujarat', city: 'Ahmedabad', _count: { ads: 432 } },
];

export const dummyAds = [
  {
    id: '1',
    title: 'iPhone 14 Pro Max - 256GB - Brand New',
    description: 'Brand new iPhone 14 Pro Max in Space Black. Unopened box, sealed. Includes all accessories. Warranty available. Reason for selling: Got a different phone.',
    price: 95000,
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800',
      'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800',
    ],
    status: 'APPROVED',
    isPremium: true,
    premiumType: 'FEATURED',
    views: 1245,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: { id: '1', name: 'Electronics', slug: 'electronics' },
    subcategory: { id: '1-1', name: 'Mobile Phones', slug: 'mobile-phones' },
    location: { id: '1', name: 'Mumbai', slug: 'mumbai' },
    user: { id: '1', name: 'Rajesh Kumar', avatar: 'https://i.pravatar.cc/150?img=12' },
    _count: { favorites: 23 }
  },
  {
    id: '2',
    title: '2020 Honda City VX - Well Maintained',
    description: 'Honda City VX 2020 model in excellent condition. Single owner, no accidents. All service records available. 35,000 km driven. Price negotiable.',
    price: 850000,
    images: [
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
    ],
    status: 'APPROVED',
    isPremium: true,
    premiumType: 'TOP',
    views: 3421,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: { id: '2', name: 'Vehicles', slug: 'vehicles' },
    subcategory: { id: '2-1', name: 'Cars', slug: 'cars' },
    location: { id: '2', name: 'Delhi', slug: 'delhi' },
    user: { id: '2', name: 'Priya Sharma', avatar: 'https://i.pravatar.cc/150?img=47' },
    _count: { favorites: 45 }
  },
  {
    id: '3',
    title: 'Modern 3-Seater Sofa - Brown Leather',
    description: 'Beautiful brown leather sofa in excellent condition. Very comfortable, perfect for living room. Moving to smaller apartment, need to sell.',
    price: 25000,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    status: 'APPROVED',
    isPremium: false,
    views: 567,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: { id: '3', name: 'Furniture', slug: 'furniture' },
    subcategory: { id: '3-1', name: 'Sofas', slug: 'sofas' },
    location: { id: '3', name: 'Bangalore', slug: 'bangalore' },
    user: { id: '3', name: 'Amit Patel', avatar: 'https://i.pravatar.cc/150?img=33' },
    _count: { favorites: 12 }
  },
  {
    id: '4',
    title: 'MacBook Pro M2 - 16GB RAM, 512GB SSD',
    description: 'MacBook Pro 14" with M2 chip. Bought 6 months ago, in perfect condition. All original accessories included. Box and warranty available.',
    price: 185000,
    images: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
    ],
    status: 'APPROVED',
    isPremium: true,
    premiumType: 'FEATURED',
    views: 2134,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: { id: '1', name: 'Electronics', slug: 'electronics' },
    subcategory: { id: '1-2', name: 'Laptops', slug: 'laptops' },
    location: { id: '4', name: 'Hyderabad', slug: 'hyderabad' },
    user: { id: '4', name: 'Sneha Reddy', avatar: 'https://i.pravatar.cc/150?img=5' },
    _count: { favorites: 67 }
  },
  {
    id: '5',
    title: 'Designer Handbags Collection - 5 Pieces',
    description: 'Collection of 5 designer handbags from premium brands. All authentic, well maintained. Selling as moving abroad. Individual prices negotiable.',
    price: 45000,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800',
    ],
    status: 'APPROVED',
    isPremium: false,
    views: 789,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: { id: '4', name: 'Fashion', slug: 'fashion' },
    subcategory: { id: '4-2', name: 'Women\'s Wear', slug: 'womens-wear' },
    location: { id: '1', name: 'Mumbai', slug: 'mumbai' },
    user: { id: '5', name: 'Anjali Mehta', avatar: 'https://i.pravatar.cc/150?img=20' },
    _count: { favorites: 34 }
  },
  {
    id: '6',
    title: 'Yamaha R15 V3 - 2021 Model',
    description: 'Yamaha R15 V3 in excellent condition. Single owner, well maintained. All service records. 12,000 km driven. Price negotiable for genuine buyers.',
    price: 165000,
    images: [
      'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800',
      'https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800',
    ],
    status: 'APPROVED',
    isPremium: true,
    premiumType: 'BUMP_UP',
    views: 1890,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: { id: '2', name: 'Vehicles', slug: 'vehicles' },
    subcategory: { id: '2-2', name: 'Bikes', slug: 'bikes' },
    location: { id: '5', name: 'Chennai', slug: 'chennai' },
    user: { id: '6', name: 'Vikram Singh', avatar: 'https://i.pravatar.cc/150?img=15' },
    _count: { favorites: 56 }
  },
  {
    id: '7',
    title: 'Samsung 55" 4K Smart TV - QLED',
    description: 'Samsung 55" QLED 4K Smart TV. Bought last year, in perfect working condition. All accessories and remote included. Moving, need to sell urgently.',
    price: 65000,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800',
      'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800',
    ],
    status: 'APPROVED',
    isPremium: false,
    views: 1234,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    category: { id: '1', name: 'Electronics', slug: 'electronics' },
    subcategory: { id: '1-4', name: 'Accessories', slug: 'accessories' },
    location: { id: '6', name: 'Pune', slug: 'pune' },
    user: { id: '7', name: 'Rahul Desai', avatar: 'https://i.pravatar.cc/150?img=51' },
    _count: { favorites: 28 }
  },
  {
    id: '8',
    title: 'Complete Home Gym Setup - All Equipment',
    description: 'Complete home gym setup including treadmill, dumbbells, bench, and more. All equipment in excellent condition. Selling as relocating.',
    price: 75000,
    images: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
    ],
    status: 'APPROVED',
    isPremium: false,
    views: 892,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    category: { id: '6', name: 'Sports', slug: 'sports' },
    subcategory: { id: '6-1', name: 'Fitness', slug: 'fitness' },
    location: { id: '2', name: 'Delhi', slug: 'delhi' },
    user: { id: '8', name: 'Deepak Verma', avatar: 'https://i.pravatar.cc/150?img=68' },
    _count: { favorites: 19 }
  },
];

export const dummyBanners = [
  {
    id: '1',
    title: 'Summer Sale - Up to 50% Off',
    image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1200',
    link: '/ads?category=electronics',
    position: 'homepage',
    isActive: true,
  },
  {
    id: '2',
    title: 'New Arrivals in Fashion',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200',
    link: '/ads?category=fashion',
    position: 'homepage',
    isActive: true,
  },
];

